<a href="https://colab.research.google.com/github/550tealeaves/data71200su24/blob/main/data71200class3_edited.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
!pip install mglearn
import mglearn
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 6.8 MB/s eta 0:00:00


# One-Hot-Encoding from Intro to Machine Learning book

In [ ]:
# The file has no headers naming the columns, so we pass header=None
# and provide the column names explicitly in "names"
adult_path = os.path.join(mglearn.datasets.DATA_PATH, "adult.data")
data = pd.read_csv(
    adult_path, header=None, index_col=False,
    names=['age', 'workclass', 'fnlwgt', 'education',  'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
           'income'])
# For illustration purposes, we only select some of the columns - creates a subset
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week',
             'occupation', 'income']]
# IPython.display allows nice output formatting within the Jupyter notebook
display(data.head())

age          workclass   education   gender  hours-per-week  \
0   39          State-gov   Bachelors     Male              40   
1   50   Self-emp-not-inc   Bachelors     Male              13   
2   38            Private     HS-grad     Male              40   
3   53            Private        11th     Male              40   
4   28            Private   Bachelors   Female              40   

           occupation  income  
0        Adm-clerical   <=50K  
1     Exec-managerial   <=50K  
2   Handlers-cleaners   <=50K  
3   Handlers-cleaners   <=50K  
4      Prof-specialty   <=50K

In [ ]:
# Checking string-encoded categorical data

print(data.gender.value_counts())

gender
 Male      21790
 Female    10771
Name: count, dtype: int64


In [ ]:
# See result of pd.get_dummies
# dummies splits up anything that is not a #
print("Original features:\n", list(data.columns), "\n")
data_dummies = pd.get_dummies(data)
print("Features after get_dummies:\n", list(data_dummies.columns))

Original features:
 ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income'] 

Features after get_dummies:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-i

In [ ]:
#splits the work categories that has lots of nested variables underneath into just a 0, 1 - so will show as true/false
#dummies does NOT work for floats - 1st must convert it to a diff data type
display(data_dummies.head())

age  hours-per-week  workclass_ ?  workclass_ Federal-gov  \
0   39              40         False                   False   
1   50              13         False                   False   
2   38              40         False                   False   
3   53              40         False                   False   
4   28              40         False                   False   

   workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  \
0                 False                    False               False   
1                 False                    False               False   
2                 False                    False                True   
3                 False                    False                True   
4                 False                    False                True   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                    False                        False                  True   
1                    False                         True                 False   
2                    False                        False                 False   
3                    False                        False                 False   
4                    False                        False                 False   

   ...  occupation_ Machine-op-inspct  occupation_ Other-service  \
0  ...                          False                      False   
1  ...                          False                      False   
2  ...                          False                      False   
3  ...                          False                      False   
4  ...                          False                      False   

   occupation_ Priv-house-serv  occupation_ Prof-specialty  \
0                        False                       False   
1                        False                       False   
2                        False                       False   
3                        False                       False   
4                        False                        True   

   occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  \
0                        False              False                     False   
1                        False              False                     False   
2                        False              False                     False   
3                        False              False                     False   
4                        False              False                     False   

   occupation_ Transport-moving  income_ <=50K  income_ >50K  
0                         False           True         False  
1                         False           True         False  
2                         False           True         False  
3                         False           True         False  
4                         False           True         False  

[5 rows x 46 columns]

In [ ]:
features = data_dummies.loc[:, 'age':'occupation_ Transport-moving']
# Extract NumPy arrays
X = features.values
y = data_dummies['income_ >50K'].values
print("X.shape: {}  y.shape: {}".format(X.shape, y.shape))

X.shape: (32561, 44)  y.shape: (32561,)


In [ ]:
#alternative to creating dummy variable
#this will also let you split the numeric features too - everything is binary
# this is good for mixed data types
from sklearn.preprocessing import OneHotEncoder

# create a DataFrame with an integer feature and a categorical string feature
demo_df = pd.DataFrame({'Integer Feature': [0, 1, 2, 1],
                        'Categorical Feature': ['socks', 'fox', 'socks', 'box']})
print('demo df')
display(demo_df)

# Setting sparse=False means OneHotEncode will return a numpy array, not a sparse matrix
ohe = OneHotEncoder(sparse=False)
print('after one hot encoding')
print(ohe.fit_transform(demo_df))

demo df


Integer Feature Categorical Feature
0                0               socks
1                1                 fox
2                2               socks
3                1                 box

after one hot encoding
[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# same thing but with scikit learn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer(
    [("scaling", StandardScaler(), ['age', 'hours-per-week']),
     ("onehot", OneHotEncoder(sparse=False), ['workclass', 'education', 'gender', 'occupation'])])